Implement MovieDaoImpl
Resci/Cinema pull request #1
Opened 2021-01-26 16:06 UTC by Resci

2021-01-26 16:20 UTC, grom4er approved these changes

2021-01-26 16:20 UTC, grom4er commented on src/main/java/com/mate/dao/MovieDaoImpl.java
> +            throw new RuntimeException("Can't insert movie entity");
Custom exception should be extended from RuntimeException;

2021-01-26 16:20 UTC, grom4er commented on src/main/java/com/mate/dao/MovieDaoImpl.java
> +            throw new RuntimeException("Can't get all movies from db");
Custom exception should be extended from RuntimeException;

2021-01-27 08:14 UTC, Sofasmile requested changes

2021-01-27 08:14 UTC, Sofasmile commented on src/main/java/com/mate/dao/MovieDaoImpl.java
> +            movie.setId(itemId);
https://mate-academy.github.io/jv-program-fulltime/03_hibernate/checklist/hibernate_01.html

2021-01-27 08:14 UTC, Sofasmile commented on src/main/java/com/mate/dao/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert movie entity");
```suggestion
            throw new DataProcessingException("Can't insert movie entity " + movie, e);
```

2021-01-27 08:14 UTC, Sofasmile commented on src/main/java/com/mate/dao/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't get all movies from db");
```suggestion
            throw new DataProcessingException("Can't get all movies from db", e);
```

2021-01-27 08:14 UTC, Sofasmile commented on src/main/java/com/mate/util/HibernateUtil.java
> +            System.err.println("Initial SessionFactory creation failed." + e);
let's remove System.err.println
better use logger for this

2021-01-27 08:14 UTC, Sofasmile commented on src/main/resources/hibernate.cfg.xml
> +</hibernate-configuration>
empty line

2021-01-27 10:53 UTC, RomanDubovskyi requested changes

2021-01-27 10:53 UTC, RomanDubovskyi commented on src/main/java/com/mate/util/HibernateUtil.java
> +    public static void shutdown() {
we don't use for now, let's remove it

2021-01-27 10:53 UTC, RomanDubovskyi commented on src/main/resources/hibernate.cfg.xml
> +        <mapping class="com.mate.model.Movie" />
```suggestion
        <property name="hibernate.hbm2ddl.auto">update</property>
        
        <mapping class="com.mate.model.Movie" />
```
 and add empty line at the end of the file

2021-01-27 11:13 UTC, RomanDubovskyi approved these changes

2021-01-27 20:35 UTC, merged